[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui: Маркировки для UI тестов.
    slow: Маркировки для медленных тестов.
    smoke: Маркировки для смоук тестов.
    critical: Маркировки для критичных тестов.
    dashboard: Маркировка для тестов, связанных с рабочей панелью.
    regression: Маркировки для регрессионных тестов.
    registration: Маркировки для тестов, связанных с регистрацией пользователя.
    authorization: Маркировки для тестов, связанных с авторизацией пользователя.
    courses: Маркировки для тестов, связанных с курсами.
